{
 "title": "Solar Viewer",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "day_interval",
    "label": "Days ",
    "query": "Last 3 days : 4,Last 7 days : 8,Last 14 days : 15,Last 30 days : 31"
   }
  ]
 },
 "panels": [
  {
   "title": "Energy produced $day_interval - chart",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "dataset": "defaultdb",
     "rawSql": "SELECT\n$__timeGroup(reporting_date, 1d) as time,\nenergy_kw\nFROM defaultdb.energy_history\nWHERE reporting_date > date_sub(now(), interval ($day_interval) day)"
    }
   ]
  },
  {
   "title": "Energy produced $day_interval KW",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "defaultdb",
     "rawSql": "SELECT SUM(energy_kw) FROM defaultdb.energy_history WHERE reporting_date > date_sub(now(), interval ($day_interval) day)"
    }
   ]
  },
  {
   "title": "Engery KW yesterday",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "defaultdb",
     "rawSql": "SELECT energy_kw FROM defaultdb.energy_history LIMIT 50 "
    }
   ]
  },
  {
   "title": "Energy produced last days - table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "dataset": "defaultdb",
     "rawSql": "SELECT energy_kw, reporting_date FROM defaultdb.energy_history LIMIT 50 "
    }
   ]
  }
 ]
}